import type { MgGameDef } from "./types";

export const GAMES: MgGameDef[] = [
  {
    id: "peon-aventurero",
    title: "Peón Aventurero",
    subtitle: "Lleva al peón hasta la corona",
    pieceKind: "p",
    pieceLabel: "Peón",
    emoji: "♟️",
    itemEmoji: "🏆",
    intro:
      "Tu peón quiere llegar a la fila 8 para coronarse. ¡Cuidado con las rocas y el fuego!",
    gradient: "from-[#fef3c7] via-[#fcd34d] to-[#d97706]",
    levels: [
      {
        index: 0,
        title: "Camino libre",
        hint: "Sube tu peón hasta la fila 8 paso a paso.",
        player: { kind: "p", at: "d2" },
        items: [],
        obstacles: [],
        goal: { kind: "reach", target: "d8" },
        maxMoves: 7,
        threeStarMoves: 6,
        twoStarMoves: 7,
      },
      {
        index: 1,
        title: "Esquiva la roca",
        hint: "Hay una roca. ¡Da la vuelta usando una captura diagonal!",
        player: { kind: "p", at: "d2" },
        items: [],
        obstacles: [
          { at: "d4", kind: "rock" },
          { at: "c3", kind: "enemy-pawn" },
        ],
        goal: { kind: "reach", target: "c8" },
        maxMoves: 7,
        threeStarMoves: 6,
        twoStarMoves: 7,
      },
      {
        index: 2,
        title: "Camino con peligros",
        hint: "Toma la diagonal para evitar la roca grande.",
        player: { kind: "p", at: "e2" },
        items: [],
        obstacles: [
          { at: "e5", kind: "rock" },
          { at: "d4", kind: "enemy-pawn" },
        ],
        goal: { kind: "reach", target: "d8" },
        maxMoves: 7,
        threeStarMoves: 6,
        twoStarMoves: 7,
      },
      {
        index: 3,
        title: "Doble obstáculo",
        hint: "Captura para abrirte paso. ¡Tu peón es valiente!",
        player: { kind: "p", at: "f2" },
        items: [],
        obstacles: [
          { at: "f5", kind: "rock" },
          { at: "e4", kind: "enemy-pawn" },
          { at: "f3", kind: "enemy-pawn" },
        ],
        goal: { kind: "reach", target: "e8" },
        maxMoves: 8,
        threeStarMoves: 7,
        twoStarMoves: 8,
      },
      {
        index: 4,
        title: "Maestro del peón",
        hint: "Planea bien tu ruta. ¡Tres capturas necesarias!",
        player: { kind: "p", at: "c2" },
        items: [],
        obstacles: [
          { at: "c4", kind: "enemy-pawn" },
          { at: "d5", kind: "enemy-pawn" },
          { at: "e6", kind: "enemy-pawn" },
          { at: "c6", kind: "rock" },
        ],
        goal: { kind: "reach", target: "f8" },
        maxMoves: 9,
        threeStarMoves: 7,
        twoStarMoves: 9,
      },
    ],
  },
  {
    id: "torre-constructora",
    title: "Torre Constructora",
    subtitle: "Captura todas las monedas",
    pieceKind: "r",
    pieceLabel: "Torre",
    emoji: "🏰",
    itemEmoji: "🪙",
    intro: "Tu Torre se mueve en línea recta. ¡Recoge todas las monedas!",
    gradient: "from-[#fde68a] via-[#f59e0b] to-[#92400e]",
    levels: [
      {
        index: 0,
        title: "Dos monedas",
        hint: "Mueve la torre en línea recta. Empieza por la moneda más cercana.",
        player: { kind: "r", at: "a1" },
        items: [
          { at: "a5", kind: "coin" },
          { at: "h5", kind: "coin" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 4,
        threeStarMoves: 2,
        twoStarMoves: 3,
      },
      {
        index: 1,
        title: "Tres monedas en L",
        hint: "Captura las tres monedas con el menor zigzag posible.",
        player: { kind: "r", at: "a1" },
        items: [
          { at: "a8", kind: "coin" },
          { at: "h8", kind: "coin" },
          { at: "h1", kind: "coin" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 6,
        threeStarMoves: 3,
        twoStarMoves: 5,
      },
      {
        index: 2,
        title: "Cuadrado de monedas",
        hint: "Cuatro monedas en las esquinas. ¡Buena ruta!",
        player: { kind: "r", at: "d4" },
        items: [
          { at: "a1", kind: "coin" },
          { at: "a8", kind: "coin" },
          { at: "h8", kind: "coin" },
          { at: "h1", kind: "coin" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 8,
        threeStarMoves: 5,
        twoStarMoves: 7,
      },
      {
        index: 3,
        title: "Con un muro",
        hint: "Una roca bloquea el camino. ¡Da la vuelta!",
        player: { kind: "r", at: "a1" },
        items: [
          { at: "a8", kind: "coin" },
          { at: "h8", kind: "coin" },
          { at: "h1", kind: "coin" },
        ],
        obstacles: [
          { at: "a5", kind: "rock" },
          { at: "h4", kind: "rock" },
        ],
        goal: { kind: "collect-all" },
        maxMoves: 8,
        threeStarMoves: 5,
        twoStarMoves: 7,
      },
      {
        index: 4,
        title: "Cinco monedas",
        hint: "Planea la ruta más corta. ¡Eres maestra de la Torre!",
        player: { kind: "r", at: "a1" },
        items: [
          { at: "a4", kind: "coin" },
          { at: "d4", kind: "coin" },
          { at: "d8", kind: "coin" },
          { at: "h8", kind: "coin" },
          { at: "h1", kind: "coin" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 10,
        threeStarMoves: 6,
        twoStarMoves: 8,
      },
    ],
  },
  {
    id: "alfil-mago",
    title: "Alfil Mago",
    subtitle: "Apaga todas las antorchas",
    pieceKind: "b",
    pieceLabel: "Alfil",
    emoji: "🧙",
    itemEmoji: "🔥",
    intro: "Tu Alfil mago se mueve en diagonal. ¡Apaga las antorchas tocándolas!",
    gradient: "from-[#fda4af] via-[#a855f7] to-[#581c87]",
    levels: [
      {
        index: 0,
        title: "Dos antorchas",
        hint: "El Alfil va en diagonal. Las antorchas están en casillas del mismo color.",
        player: { kind: "b", at: "c1" },
        items: [
          { at: "a3", kind: "torch" },
          { at: "h6", kind: "torch" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 4,
        threeStarMoves: 2,
        twoStarMoves: 3,
      },
      {
        index: 1,
        title: "Tres en zigzag",
        hint: "Tres antorchas en diagonales distintas. ¡Planéalo bien!",
        player: { kind: "b", at: "c1" },
        items: [
          { at: "f4", kind: "torch" },
          { at: "h6", kind: "torch" },
          { at: "a3", kind: "torch" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 5,
        threeStarMoves: 3,
        twoStarMoves: 4,
      },
      {
        index: 2,
        title: "Antorchas en cruz",
        hint: "Las cuatro antorchas están en una cruz diagonal.",
        player: { kind: "b", at: "d4" },
        items: [
          { at: "a1", kind: "torch" },
          { at: "h8", kind: "torch" },
          { at: "a7", kind: "torch" },
          { at: "g1", kind: "torch" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 6,
        threeStarMoves: 4,
        twoStarMoves: 5,
      },
      {
        index: 3,
        title: "Con piedra mágica",
        hint: "Hay una roca diagonal. Encuentra el camino.",
        player: { kind: "b", at: "c1" },
        items: [
          { at: "f4", kind: "torch" },
          { at: "h6", kind: "torch" },
          { at: "a3", kind: "torch" },
        ],
        obstacles: [
          { at: "e3", kind: "rock" },
        ],
        goal: { kind: "collect-all" },
        maxMoves: 6,
        threeStarMoves: 4,
        twoStarMoves: 5,
      },
      {
        index: 4,
        title: "Maestra del fuego",
        hint: "¡Cinco antorchas! Necesitas precisión mágica.",
        player: { kind: "b", at: "c1" },
        items: [
          { at: "a3", kind: "torch" },
          { at: "f4", kind: "torch" },
          { at: "h6", kind: "torch" },
          { at: "c5", kind: "torch" },
          { at: "g7", kind: "torch" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 8,
        threeStarMoves: 5,
        twoStarMoves: 7,
      },
    ],
  },
  {
    id: "caballo-saltarin",
    title: "Caballo Saltarín",
    subtitle: "Recoge todas las zanahorias",
    pieceKind: "n",
    pieceLabel: "Caballo",
    emoji: "🐴",
    itemEmoji: "🥕",
    intro: "Tu Caballo brinca en L. ¡Salta sobre las rocas y recoge zanahorias!",
    gradient: "from-[#fed7aa] via-[#f97316] to-[#9a3412]",
    levels: [
      {
        index: 0,
        title: "Una zanahoria",
        hint: "Salta en L para llegar a la zanahoria.",
        player: { kind: "n", at: "b1" },
        items: [{ at: "c3", kind: "carrot" }],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 2,
        threeStarMoves: 1,
        twoStarMoves: 2,
      },
      {
        index: 1,
        title: "Dos zanahorias",
        hint: "Dos saltos planeados. ¡Recoge ambas!",
        player: { kind: "n", at: "b1" },
        items: [
          { at: "c3", kind: "carrot" },
          { at: "f6", kind: "carrot" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 5,
        threeStarMoves: 3,
        twoStarMoves: 4,
      },
      {
        index: 2,
        title: "Salta las rocas",
        hint: "El Caballo salta sobre rocas. ¡Aprovecha!",
        player: { kind: "n", at: "b1" },
        items: [
          { at: "c3", kind: "carrot" },
          { at: "e4", kind: "carrot" },
        ],
        obstacles: [
          { at: "c2", kind: "rock" },
          { at: "d3", kind: "rock" },
        ],
        goal: { kind: "collect-all" },
        maxMoves: 5,
        threeStarMoves: 3,
        twoStarMoves: 4,
      },
      {
        index: 3,
        title: "Tres en triángulo",
        hint: "Tres zanahorias. Encuentra la ruta más corta.",
        player: { kind: "n", at: "b1" },
        items: [
          { at: "a3", kind: "carrot" },
          { at: "c5", kind: "carrot" },
          { at: "e3", kind: "carrot" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 7,
        threeStarMoves: 5,
        twoStarMoves: 6,
      },
      {
        index: 4,
        title: "Tour del caballo",
        hint: "Cuatro zanahorias en cuatro esquinas. ¡A galopar!",
        player: { kind: "n", at: "d4" },
        items: [
          { at: "b3", kind: "carrot" },
          { at: "f3", kind: "carrot" },
          { at: "b5", kind: "carrot" },
          { at: "f5", kind: "carrot" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 7,
        threeStarMoves: 4,
        twoStarMoves: 6,
      },
    ],
  },
  {
    id: "reina-del-reino",
    title: "Reina del Reino",
    subtitle: "Caza dragones traviesos",
    pieceKind: "q",
    pieceLabel: "Reina",
    emoji: "👑",
    itemEmoji: "🐲",
    intro: "Tu Reina puede ir a donde quiera. ¡Caza todos los dragones rivales!",
    gradient: "from-[#fbcfe8] via-[#ec4899] to-[#9d174d]",
    levels: [
      {
        index: 0,
        title: "Dos dragones",
        hint: "Tu Reina va recto y diagonal. ¡Cómelos rápido!",
        player: { kind: "q", at: "d1" },
        items: [
          { at: "d8", kind: "dragon" },
          { at: "h4", kind: "dragon" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 3,
        threeStarMoves: 2,
        twoStarMoves: 3,
      },
      {
        index: 1,
        title: "Tres dragones",
        hint: "Tres dragones, ruta inteligente.",
        player: { kind: "q", at: "d1" },
        items: [
          { at: "a4", kind: "dragon" },
          { at: "h4", kind: "dragon" },
          { at: "d8", kind: "dragon" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 4,
        threeStarMoves: 3,
        twoStarMoves: 4,
      },
      {
        index: 2,
        title: "Cuatro dragones",
        hint: "Cuatro dragones en posiciones lejanas.",
        player: { kind: "q", at: "d4" },
        items: [
          { at: "a1", kind: "dragon" },
          { at: "h1", kind: "dragon" },
          { at: "a8", kind: "dragon" },
          { at: "h8", kind: "dragon" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 6,
        threeStarMoves: 4,
        twoStarMoves: 5,
      },
      {
        index: 3,
        title: "Dragones con muros",
        hint: "Hay rocas. ¡Encuentra ángulos limpios!",
        player: { kind: "q", at: "d1" },
        items: [
          { at: "a4", kind: "dragon" },
          { at: "h4", kind: "dragon" },
          { at: "d8", kind: "dragon" },
        ],
        obstacles: [
          { at: "d4", kind: "rock" },
        ],
        goal: { kind: "collect-all" },
        maxMoves: 5,
        threeStarMoves: 3,
        twoStarMoves: 4,
      },
      {
        index: 4,
        title: "La Reina total",
        hint: "Cinco dragones. ¡Sé reina del reino!",
        player: { kind: "q", at: "d1" },
        items: [
          { at: "a4", kind: "dragon" },
          { at: "h4", kind: "dragon" },
          { at: "d8", kind: "dragon" },
          { at: "a8", kind: "dragon" },
          { at: "h8", kind: "dragon" },
        ],
        obstacles: [],
        goal: { kind: "collect-all" },
        maxMoves: 8,
        threeStarMoves: 5,
        twoStarMoves: 7,
      },
    ],
  },
  {
    id: "rey-valiente",
    title: "Rey Valiente",
    subtitle: "Llega a la torre amiga sin pasar por fuego",
    pieceKind: "k",
    pieceLabel: "Rey",
    emoji: "🤴",
    itemEmoji: "🏰",
    intro: "Tu Rey debe llegar hasta la torre amiga sin caminar sobre el fuego.",
    gradient: "from-[#fef9c3] via-[#facc15] to-[#854d0e]",
    levels: [
      {
        index: 0,
        title: "Camino limpio",
        hint: "Camina paso a paso hacia la torre amiga.",
        player: { kind: "k", at: "a1" },
        items: [{ at: "h8", kind: "ally-rook" }],
        obstacles: [],
        goal: { kind: "reach", target: "h8" },
        maxMoves: 9,
        threeStarMoves: 7,
        twoStarMoves: 8,
      },
      {
        index: 1,
        title: "Camino con fuego",
        hint: "Esquiva las casillas rojas, ¡queman!",
        player: { kind: "k", at: "a1" },
        items: [{ at: "h1", kind: "ally-rook" }],
        obstacles: [
          { at: "d1", kind: "fire" },
          { at: "d2", kind: "fire" },
        ],
        goal: { kind: "reach", target: "h1" },
        maxMoves: 9,
        threeStarMoves: 7,
        twoStarMoves: 8,
      },
      {
        index: 2,
        title: "Pasaje difícil",
        hint: "Hay un pasillo de fuego. ¡Encuentra el hueco!",
        player: { kind: "k", at: "a1" },
        items: [{ at: "h8", kind: "ally-rook" }],
        obstacles: [
          { at: "d4", kind: "fire" },
          { at: "e4", kind: "fire" },
          { at: "f4", kind: "fire" },
          { at: "g4", kind: "fire" },
        ],
        goal: { kind: "reach", target: "h8" },
        maxMoves: 11,
        threeStarMoves: 8,
        twoStarMoves: 10,
      },
      {
        index: 3,
        title: "Doble pasillo",
        hint: "Dos pasillos de fuego. ¡Sortea con cuidado!",
        player: { kind: "k", at: "a1" },
        items: [{ at: "h8", kind: "ally-rook" }],
        obstacles: [
          { at: "c2", kind: "fire" },
          { at: "c3", kind: "fire" },
          { at: "c4", kind: "fire" },
          { at: "f5", kind: "fire" },
          { at: "f6", kind: "fire" },
          { at: "f7", kind: "fire" },
        ],
        goal: { kind: "reach", target: "h8" },
        maxMoves: 12,
        threeStarMoves: 9,
        twoStarMoves: 11,
      },
      {
        index: 4,
        title: "Corredor del valor",
        hint: "Eres el Rey más valiente. ¡Atrévete!",
        player: { kind: "k", at: "a1" },
        items: [{ at: "h8", kind: "ally-rook" }],
        obstacles: [
          { at: "b3", kind: "fire" },
          { at: "c4", kind: "fire" },
          { at: "d5", kind: "fire" },
          { at: "e6", kind: "fire" },
          { at: "f7", kind: "fire" },
        ],
        goal: { kind: "reach", target: "h8" },
        maxMoves: 12,
        threeStarMoves: 9,
        twoStarMoves: 11,
      },
    ],
  },
];

export function getGame(id: string) {
  return GAMES.find((g) => g.id === id);
}
